### ISSUE TITLE
Wish List

### ISSUE THREAD

**Issue by t104360088** [rtchagas/pingplacepicker#15]
Hi, @rtchagas 
I am university student in taiwan
I have a app about hail a taxi for user, but place picker deprecated by Google
This library is useful for me, and  I have a bold request

May you add the function about the following
1. Set country or set latitude and longitude to narrow the range in no positioning
2. Set multilingual to change text

Thanks for your reading

**Comment by rtchagas** [comment]
Hi @t104360088 

Regarding the request "2. Set multilingual to change text", you can easily translate the PING resources in you app.
When building the app your resources will overwrite PING resources.

Just copy all resources from https://github.com/rtchagas/pingplacepicker/blob/master/library/src/main/res/values/strings.xml to your app's resources and translate them.

You can also contribute to PING with a Pull Request translating those strings to your language. I would be glad to merge it to PING.

Regarding the first request, what do you mean by narrowing the range in no positioning?

**Comment by t104360088** [comment]
Thanks for your reply, @rtchagas 
If I do not have position, I will get this view
But I want to order the specific location to narrow down
Could I get the view by set latitude and longitude or country?

![61139481_2227698287491642_6069980531003490304_n](https://user-images.githubusercontent.com/32124047/58460645-a7964f00-8160-11e9-85eb-2675bb56aad3.jpg)

**Comment by rtchagas** [comment]
Hi @t104360088 

I was implementing your request to "narrow the range in no positioning" but I found an issue with Google Places API that made it impossible.

Places API needs the Location to be turned on in order to retrieve search results.

I tried to manually set the initial location when there is no GPS but the Places API returned me an error and no results could be displayed.

Unfortunately to use PING we must have Location enabled.

I'm closing this issue. 
Thank you so much for your support.
