### ISSUE TITLE
Tablet : searchbar is hidden in samsung S3 tab

### ISSUE THREAD

**Issue by bhavesh-hirpara** [rtchagas/pingplacepicker#19]
![image](https://user-images.githubusercontent.com/1277011/58799440-fc373f80-8622-11e9-922d-5a2540d265db.png)

Can anyone know the solution?

**Comment by rtchagas** [comment]
Hi @bhavesh-hirpara 

This is the expected behavior on large screens.
https://github.com/rtchagas/pingplacepicker/blob/e9338f5c0a3d4c6247d880ff51c8d5c1c32f2035/library/src/main/res/values-w600dp/config.xml#L3

You can override it by setting that flag to true.

However you can always access the search function by scrolling up the places list.
