### ISSUE TITLE
support for setLatLngBounds

### ISSUE THREAD

**Issue by ArdentZeal** [rtchagas/pingplacepicker#22]
Hey there,

Th old google place picker had the ablity to set an initial location different than the current location via builder.setLatLngBounds(latLngBounds)

I need to be able to edit already picked locations so this would be really helpful. Is there support planned for that?

**Comment by rtchagas** [comment]
Hi @ArdentZeal 

This is exactly the key difference between PING and Google's:
https://github.com/rtchagas/pingplacepicker#a-key-difference

In order to set a predefined location we must use /nearbysearch queries that cost more money. This can be done but I don't know whether it is worthy.

I should think more about this... Maybe we could just fetch the initial list of places based on a custom location.

Meanwhile, you can search for places in a different area by using the search bar.

**Comment by ArdentZeal** [comment]
I would be fine paying the nearbysearch for the initial location. 

Cheers,
Matthias

**Comment by rtchagas** [comment]
This commit https://github.com/rtchagas/pingplacepicker/commit/64ac79d58bb41f4fe48407c92febd62d66eefa9f enables /nearbysearch queries.

I'm validating the new solution and hope to publish the library soon.

**Comment by rtchagas** [comment]
https://github.com/rtchagas/pingplacepicker/releases/tag/1.1.0
