### ISSUE TITLE
Button to update the places that are nearby

### ISSUE THREAD

**Issue by Ivrean** [rtchagas/pingplacepicker#23]
Can you add a button to force the update of places? Also add a flag when calling, show this button or not.

**Comment by kkostrubiec** [comment]
this would be nice improvement :)

**Comment by kkostrubiec** [comment]
@Ivrean I've done this (but without flag) here https://github.com/rtchagas/pingplacepicker/pull/26

**Comment by rtchagas** [comment]
Hi @kkostrubiec , thanks for the pull request.

I reviewed and the way it was implemented, it does not refresh the places properly.
The GeoCoding API that you used may retrieve places as addresses (street, number, city, etc). It doesn't always return POIs (shops, restaurants, stations, etc) as we want.

In order to get/refresh places based on a location we must use the /nearbysearch in Maps API.
I started to implemented it and, therefore, I'm going to merge this issue into this one #22 

Regarging the Multi-Dex, if you deploy the app to a device with API 21+ or that has enabled Proguard/R8, it will fit in a single dex. That's why I didn't enable multidex.

Please follow that issue to get updates.

Thank you!
