### ISSUE TITLE
Wrong lat and long while picking the centered marker position

### ISSUE THREAD

**Issue by ritesh-dubey** [rtchagas/pingplacepicker#4]
When I use the latitude and longitude received from:
 `Place place = PingPlacePicker.Companion.getPlace(data);`

and use the same lat-long in google maps, the marker instead of pointing to the location what I selected in the library now points to some nearby location. Can you please help me out with this issue. Please refer the screenshots for your reference.
![Screenshot_20190329-104815](https://user-images.githubusercontent.com/2135148/55211438-fdf31a00-5211-11e9-9b44-19459183a217.png)
![Screenshot_20190329-104901](https://user-images.githubusercontent.com/2135148/55211451-08151880-5212-11e9-9546-d047e41ebdb3.png)

**Comment by rtchagas** [comment]
Hi @ritesh-dubey 

I was digging into this issue for I while, but I believe that it is the expected behavior.

When you point the map to a location and select it, PING uses the Maps' Reverse Geolocation API.

That API requires a Lat/Lng position and returns the **best Place object that matches that position**. 

What means that the API will return a **Place** that does exist in that position. However, the registered Lat/Lng (in Maps API) for the returned Place object might be different from what you were pointing to.

Unfortunately this is a limitation that we can't work on.

Thanks
